# Generated by Django 5.0.4 on 2024-04-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_description_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='source',
            new_name='url',
        ),
    ]
