# Generated by Django 5.0.4 on 2024-04-18 07:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_source_postimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='url',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
