# Generated by Django 5.0.4 on 2024-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motel',
            name='lat',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motel',
            name='lon',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
