# Generated by Django 5.0.4 on 2024-04-13 02:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0002_motel_lat_motel_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
