# Generated by Django 5.0.4 on 2024-04-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0004_alter_user_avatar_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='created_date',
            field=models.DateField(auto_now_add=True, default='2024-04-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
