# Generated by Django 5.0.4 on 2024-04-17 11:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0005_follow_created_date_follow_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motel',
            old_name='dientich',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='motel',
            old_name='diachikhac',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='motel',
            old_name='quanhuyen',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='motel',
            old_name='tinhtp',
            new_name='other_address',
        ),
        migrations.RenameField(
            model_name='motel',
            old_name='xaphuong',
            new_name='ward',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
