# Generated by Django 5.0.4 on 2024-04-18 07:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0007_rename_source_motelimage_url_alter_motelimage_motel'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='period',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motelimage',
            name='url',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
