# Generated by Django 5.0.4 on 2024-04-25 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0010_alter_price_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 10, 3, 44, 430254)),
        ),
    ]
