# Generated by Django 5.0.4 on 2024-04-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0012_remove_reservation_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expiration',
            field=models.DateTimeField(default='2024-04-28 10:51:12'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='motel',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='motelimage',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
