# Generated by Django 5.0.4 on 2024-05-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0013_reservation_expiration_alter_follow_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiration',
            field=models.DateTimeField(default='2024-05-04 14:09:27'),
        ),
    ]
