# Generated by Django 5.0.4 on 2024-05-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0015_alter_reservation_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='expiration',
            field=models.DateTimeField(default='2024-05-04 22:16:59'),
        ),
    ]
