# Generated by Django 5.0.4 on 2024-05-01 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0016_alter_reservation_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motelimage',
            name='motel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='motel.motel'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiration',
            field=models.DateTimeField(default='2024-05-04 22:27:35'),
        ),
    ]
