# Generated by Django 5.0.4 on 2024-05-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0018_alter_reservation_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motel',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='motel',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiration',
            field=models.DateTimeField(default='2024-05-30 10:10:26'),
        ),
    ]
